version: "3.7"

services:
  portainer-agent:
    image: portainer/agent:1.5.1
    environment:
      # AGENT_PORT: 9001
      LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - internal
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer:1.23.0
    command: -H "tcp://tasks.portainer_portainer-agent:9001" --tlsskipverify
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    networks:
      - internal
      - proxy
    deploy:
      placement:
        constraints:
          - 'node.role == manager'
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        - "traefik.http.routers.portainer.rule=Host(`portainer.${TRAEFIK_DOMAIN}`)"
        - "traefik.http.routers.portainer.entrypoints=https"
        - "traefik.http.routers.portainer.tls=true"
        - "traefik.http.routers.portainer.tls.certresolver=le"
        # Swarm Mode
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"

networks:
  proxy:
    external: true
    driver: overlay
  internal:
    external: false
    driver: overlay

